FROM node:14-buster AS setup
WORKDIR /app
COPY frontend/package.json ./
RUN npm install
COPY frontend .

FROM setup AS build
ENV NODE_ENV=production
WORKDIR /build
COPY --from=setup /app ./
RUN npm run build

FROM node:14-alpine AS production
ENV NODE_ENV=production
WORKDIR /app
COPY --chown=node:node --from=build /build/package*.json ./
COPY --chown=node:node --from=build /build/.next ./.next
COPY --chown=node:node --from=build /build/public ./public
RUN npm install next && chown node:node -R node_modules package-lock.json

EXPOSE 3000
CMD npm run start

