FROM node:14-buster AS setup
WORKDIR /app
COPY frontend/package.json ./
RUN npm install
COPY frontend .

FROM setup AS build
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_DOC_URL
ARG NEXT_PUBLIC_GRAPHQL_URL
ARG NEXT_PUBLIC_GA_ID
ARG NEXT_PUBLIC_CLIENT_ORIGIN

# https://www.saltycrane.com/blog/2021/04/buildtime-vs-runtime-environment-variables-nextjs-docker/
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_DOC_URL=$NEXT_PUBLIC_API_DOC_URL
ENV NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_CLIENT_ORIGIN=$NEXT_PUBLIC_CLIENT_ORIGIN
ENV NODE_ENV=production

WORKDIR /build
COPY --from=setup /app ./
RUN npm run build

FROM node:14-alpine AS production
ENV NODE_ENV=production
WORKDIR /app
COPY --chown=node:node --from=build /build/package*.json ./
COPY --chown=node:node --from=build /build/.next ./.next
COPY --chown=node:node --from=build /build/public ./public
RUN npm install next && chown node:node -R node_modules package-lock.json

EXPOSE 3000
CMD npm run start

